###################  spring配置  ###################
spring:
  redis:
    redisson:
      config: classpath:application-redisson.yml
  rabbitmq:
    host: rabbitmq.mycs.cn
    port: 5673
    username: mycs_zipkin
    password: 5os2fXNxzocShCNy