logging:
  level.root: info
  level.cn.mycs: debug
  path: /wdata/weblog/mycs-business-examine-server/
  file: mycs-business-examine-server-runtime.log
  pattern:
    file:
      "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} [%4line 行]: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    console:
      "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan} [%clr(%4line)行]    %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
