spring:
  datasource:
    url: jdbc:mysql://db.master.mycs.uat:3307/mycs_basic?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: aulgx
    password: tvxuhJT9eRDPuACB